apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-ubuntu-deploy
    labels:
        app: node-ubuntu
        type: app
spec:
    selector:
        matchLabels:
            app: node-ubuntu
    replicas: 1
    strategy: 
      type: RollingUpdate
    template:
        metadata:
            labels:
                app: node-ubuntu
        spec:
            restartPolicy: Always
            containers:
            - name: node-ubuntu
              image: gbcdocker/node-ubuntu
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              resources: 
                requests:
                  memory: "200Mi"
                  cpu: "50m"
                limits:
                  memory: "300Mi"
                  cpu: "60m"
         #   Docker repo required if pulling image from a private repo
         #   imagePullSecrets:
         #   - name: regcred
