apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: node-ubuntu-hpa
  namespace: default
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: node-ubuntu-deploy
  minReplicas: 1
  maxReplicas: 50000
  targetCPUUtilizationPercentage: 95
