apiVersion: v1
kind: Service
metadata:
    name: node-ubuntu
    labels:
        app: node-ubuntu
spec:
    type: LoadBalancer
    #loadBalancerIP: 192.168.3.3
    clusterIP: 10.96.2.3
    selector:
      app: deviceop
    ports: 
    - name: "http"
      port: 80
      targetPort: 80
    - name: 'https'
      port: 443
      targetPort: 443
