apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: mongodb-hpa
  namespace: default
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb-set
  minReplicas: 1
  maxReplicas: 50000
  targetCPUUtilizationPercentage: 95
