apiVersion: v1
kind: Service
metadata:
    name: mongodb
    labels:
        app: mongodb
spec:
    type: ClusterIP
    #clusterIP: 10.96.2.13
    selector:
      app: mongodb
    ports: 
    - name: "default"
      port: 27017
      targetPort: 27017
    - name: "http"
      port: 80
      targetPort: 27017
