apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-set
  labels: 
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: mongodb-pvc
      initContainers:
      - name: fix-the-volume-permission
        image: busybox
        command:
        - sh
        - -c
        -  chown -R 1001:1001 /bitnami/mongodb/data
        volumeMounts:
        - name: mongodb-volume
          mountPath: /bitnami/mongodb/data
      containers:
        - name: mongodb
          image: bitnami/mongodb:4.4.5
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: 500Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-volume
              mountPath: /bitnami/mongodb/data
      #imagePullSecrets:
       # - name: regcred
